/* Data from the previous month is used to check for coding changes since the last extraction */
/* Run the following to transfer PEDW to previous month's table */

DELETE FROM SAILW0572V.VB_PEDW_EPS_2015ON_PREV;

INSERT INTO SAILW0572V.VB_PEDW_EPS_2015ON_PREV 
	(SELECT * FROM SAILW0572V.VB_PEDW_EPS_2015ON);

/* Run the following to clear previous versions of 2015ON TABLES */
		
DELETE FROM SAILW0572V.VB_PEDW_EPS_2015ON_PRE;

DELETE FROM SAILW0572V.VB_PEDW_EPS_2015ON_ALF;

DELETE FROM SAILW0572V.VB_PEDW_EPS_2015ON_ALF_SICD;

DELETE FROM SAILW0572V.VB_PEDW_EPS_2015ON_ALF_SICD_OPCS;

DELETE FROM SAILW0572V.VB_PEDW_EPS_2015ON_ALF_SICD_OPCS_HB;

DROP TABLE SAILW0572V.VB_PEDW_EPS_2015ON;

DELETE FROM SAILW0572V.VB_PEDW_EXTRACT_DATES;

DELETE FROM SAILW0572V.VB_PEDW_FIRST_REPORT_INSTANCE_UNIQUE;

DELETE FROM SAILW0572V.VB_PEDW_FIRST_ICD_INSTANCE_UNIQUE;

DELETE FROM SAILW0572V.VB_PEDW_FIRST_OPCS_INSTANCE_UNIQUE;

/* Data run from April 2016 */

/* ACTION - Table names must be updated with the latest versions prior to running*/

/* Run the following to update the data tables based on the latest available extraction */

INSERT INTO SAILW0572V.VB_PEDW_EPS_2015ON_PRE
			(ALF_PE, 
			ALF_STS_CD, 
			PROV_UNIT_CD, 
			SPELL_NUM_PE,
			ADMIS_MTHD_CD,
			DIAG_CD_123,
			DIAG_CD_1234,
			OPER_CD_123,
			OPER_CD,
			EPI_STR_DT, 
			EPI_END_DT, 
			EPI_END_YR,
			CHAPTER_NUMBER,
			CATEGORY_1_DESCRIPTION,
			EPI_END_MT,
			EPI_END_WK,
			EPI_NUM,
			FINISHED_EPI_FLG,
			SPELL_ID,
			EPI_ID,
			OPER_INIT)
		SELECT	sp.ALF_PE, 
				sp.ALF_STS_CD, 
				sp.PROV_UNIT_CD, 
				sp.SPELL_NUM_PE,
				sp.ADMIS_MTHD_CD,
				ep.DIAG_CD_123,
				ep.DIAG_CD_1234,
				ep.OPER_CD_123,
				ep.OPER_CD, 
				ep.EPI_STR_DT, 
				ep.EPI_END_DT, 
				ep.EPI_END_YR,
				icd.CHAPTER_NUMBER,
				icd.CATEGORY_1_DESCRIPTION,
				MONTH(ep.EPI_END_DT),
				WEEK(ep.EPI_END_DT),
				ep.EPI_NUM,
				ep.FINISHED_EPI_FLG,
				ep.PROV_UNIT_CD||ep.SPELL_NUM_PE,
				ep.PROV_UNIT_CD||ep.SPELL_NUM_PE||EPI_NUM,
				SUBSTRING(ep.OPER_CD,1,1)
		FROM SAIL0572V.PEDW_EPISODE_20210926 ep
			LEFT JOIN SAIL0572V.PEDW_SPELL_20210926 sp
				ON ep.PROV_UNIT_CD = sp.PROV_UNIT_CD
				AND ep.SPELL_NUM_PE = sp.SPELL_NUM_PE --link PEDW EPI and SPELL on prov unit cd and spell num--
			LEFT JOIN (SELECT * FROM SAILUKHDV.ICD10_CODES_AND_TITLES_AND_METADATA
				WHERE SAILUKHDV.ICD10_CODES_AND_TITLES_AND_METADATA.ICD_VERSION = 'ICD10 5th Edition') AS icd
					ON ep.DIAG_CD_1234 = icd.ALT_CODE
			LEFT JOIN (SELECT * FROM SAILUKHDV.OPCS4_CODES_AND_TITLES
				WHERE SAILUKHDV.OPCS4_CODES_AND_TITLES.OPCS_VERSION = '4.9') AS opcs
					ON ep.OPER_CD = opcs.CODE_WITHOUT_DECIMAL
					WHERE ep.EPI_END_DT > '2016-03-31';
	
INSERT INTO SAILW0572V.VB_PEDW_EPS_2015ON_ALF
	(SELECT pre.* FROM SAILW0572V.VB_PEDW_EPS_2015ON_PRE AS pre
	WHERE (pre.ALF_STS_CD IS NOT NULL
			AND pre.ALF_STS_CD IN ('1', '4', '39'))
		AND pre.EPI_END_DT >= '2015-04-01');

INSERT INTO SAILW0572V.VB_PEDW_EPS_2015ON_ALF_SICD
	(SELECT ALF.* FROM SAILW0572V.VB_PEDW_EPS_2015ON_ALF AS ALF
	LEFT JOIN SAILW0572V.VB_SENSITIVE_ICD_CODES AS sicd
		ON ALF.DIAG_CD_1234 = sicd.code
	WHERE sicd.code IS NULL);
	
INSERT INTO SAILW0572V.VB_PEDW_EPS_2015ON_ALF_SICD_OPCS
	(SELECT SICD.* FROM SAILW0572V.VB_PEDW_EPS_2015ON_ALF_SICD AS SICD
	LEFT JOIN SAILW0572V.VB_SENS_OPCS_COMBINED AS opcs
		ON SICD.OPER_CD = opcs.OPER_CD_1234
	WHERE opcs.OPER_CD_1234 IS NULL);

INSERT INTO SAILW0572V.VB_PEDW_EPS_2015ON_ALF_SICD_OPCS_HB
	(SELECT OPCS.* FROM SAILW0572V.VB_PEDW_EPS_2015ON_ALF_SICD_OPCS AS OPCS
	WHERE OPCS.PROV_UNIT_CD IN ('7A1', '7A2', '7A3', '7A4', '7A5', '7A6', '7A7', 'RQF'));

CREATE TABLE SAILW0572V.VB_PEDW_EPS_2015ON AS
	(SELECT	*
		FROM SAILW0572V.VB_PEDW_EPS_2015ON_ALF_SICD_OPCS_HB) WITH NO DATA;
	
INSERT INTO SAILW0572V.VB_PEDW_EPS_2015ON
	(SELECT eps.* 
	FROM SAILW0572V.VB_PEDW_EPS_2015ON_ALF_SICD_OPCS_HB AS eps
		LEFT JOIN SAIL0572V.ADDE_DEATHS_20210902 AS dd
			ON eps.ALF_PE = dd.ALF_PE 
			WHERE eps.EPI_STR_DT <= dd.DEATH_DT
			OR dd.DEATH_DT IS NULL);
		
/* First episode table used to build a history of when episodes first had a diagnosis code recorded*/
/* ACTION - Update FROM Table with the latest extract date prior to running*/
		
INSERT INTO SAILW0572V.VB_PEDW_FIRST_REPORT_INSTANCE
	(SELECT eps.PROV_UNIT_CD||eps.SPELL_NUM_PE||eps.EPI_NUM AS EPI_ID,
			eps.DIAG_CD_1234,
			eps.AVAIL_FROM_DT
		FROM SAIL0572V.PEDW_EPISODE_20210926 AS eps
		WHERE eps.EPI_END_DT > '2019-12-31');
	
/* First ICD instance table used to build a history of when episodes first had a diagnosis code recorded*/
/* ACTION - Update FROM Table with the latest extract date prior to running*/
	
INSERT INTO SAILW0572V.VB_PEDW_FIRST_ICD_INSTANCE
	(SELECT eps.PROV_UNIT_CD||eps.SPELL_NUM_PE||eps.EPI_NUM AS EPI_ID,
			eps.DIAG_CD_1234,
			eps.AVAIL_FROM_DT
		FROM SAIL0572V.PEDW_EPISODE_20210926 AS eps
		WHERE eps.EPI_END_DT > '2019-12-31'
		AND eps.DIAG_CD_1234 IS NOT NULL);
	
/* First OPCS instance table used to build a history of when episodes first had an operation code recorded*/
/* ACTION - Update FROM Table with the latest extract date prior to running*/
	
INSERT INTO SAILW0572V.VB_PEDW_FIRST_OPCS_INSTANCE
	(SELECT eps.PROV_UNIT_CD||eps.SPELL_NUM_PE||eps.EPI_NUM AS EPI_ID,
			eps.OPER_CD,
			eps.AVAIL_FROM_DT
		FROM SAIL0572V.PEDW_EPISODE_20210926 AS eps
		WHERE eps.EPI_END_DT > '2019-12-31'
		AND eps.DIAG_CD_1234 IS NOT NULL);
	
/*Run the following to produce table of the 6 most recent extract dates used to generate loops and charts in R */

INSERT INTO SAILW0572V.VB_PEDW_EXTRACT_DATES
	(SELECT TRIM(fst.AVAILABLE_FROM_DT)
		FROM SAILW0572V.VB_PEDW_FIRST_REPORT_INSTANCE AS fst
			GROUP BY TRIM(fst.AVAILABLE_FROM_DT)
			ORDER BY TRIM(fst.AVAILABLE_FROM_DT) DESC)
		LIMIT 6;

/* Update the main PEDW table with the first report instance*/
/* Add First report date column to main table */

ALTER TABLE SAILW0572V.VB_PEDW_EPS_2015ON
	ADD COLUMN FIRST_REPORT_DT DATE;

/*Insert the first report date into table (step added to reduce report run time)*/

INSERT INTO SAILW0572V.VB_PEDW_FIRST_REPORT_INSTANCE_UNIQUE
	(SELECT eps.EPI_ID,
			MIN(eps.AVAILABLE_FROM_DT)
		FROM SAILW0572V.VB_PEDW_FIRST_REPORT_INSTANCE AS eps
			GROUP BY eps.EPI_ID);
		
/*Set the min report date to the first extract date of interest for R charts (only the last 7 extract dates are displayed)*/
		
UPDATE SAILW0572V.VB_PEDW_FIRST_REPORT_INSTANCE_UNIQUE AS fst
	SET fst.FIRST_REPORT_DT = CASE WHEN fst.FIRST_REPORT_DT < (SELECT min(dts.EXTRACT_DT) FROM SAILW0572V.VB_PEDW_EXTRACT_DATES AS dts)
			THEN (SELECT min(dts.EXTRACT_DT) FROM SAILW0572V.VB_PEDW_EXTRACT_DATES AS dts)
	ELSE fst.FIRST_REPORT_DT
		END;
	
/*update main table with the first report date*/
	
UPDATE SAILW0572V.VB_PEDW_EPS_2015ON eps
	SET eps.FIRST_REPORT_DT = (SELECT fst.FIRST_REPORT_DT
	FROM SAILW0572V.VB_PEDW_FIRST_REPORT_INSTANCE_UNIQUE AS fst
			WHERE eps.EPI_ID = fst.EPI_ID);

/* Update the main PEDW table with the first diagnosis code date*/
		
ALTER TABLE SAILW0572V.VB_PEDW_EPS_2015ON
	ADD COLUMN FIRST_ICD_DT DATE;

INSERT INTO SAILW0572V.VB_PEDW_FIRST_ICD_INSTANCE_UNIQUE
	(SELECT eps.EPI_ID,
			MIN(eps.AVAILABLE_FROM_DT)
		FROM SAILW0572V.VB_PEDW_FIRST_ICD_INSTANCE AS eps
			GROUP BY eps.EPI_ID);
		
UPDATE SAILW0572V.VB_PEDW_FIRST_ICD_INSTANCE_UNIQUE AS fst
	SET fst.FIRST_ICD_DT = CASE WHEN fst.FIRST_ICD_DT < (SELECT min(dts.EXTRACT_DT) FROM SAILW0572V.VB_PEDW_EXTRACT_DATES AS dts)
			THEN (SELECT min(dts.EXTRACT_DT) FROM SAILW0572V.VB_PEDW_EXTRACT_DATES AS dts)
	ELSE fst.FIRST_ICD_DT
		END;

UPDATE SAILW0572V.VB_PEDW_EPS_2015ON eps
	SET eps.FIRST_ICD_DT = (SELECT fst.FIRST_ICD_DT
	FROM SAILW0572V.VB_PEDW_FIRST_ICD_INSTANCE_UNIQUE AS fst
			WHERE eps.EPI_ID = fst.EPI_ID)
			WHERE eps.DIAG_CD_1234 IS NOT NULL;
		
/* Update the main PEDW table with the first operation code date*/
		
ALTER TABLE SAILW0572V.VB_PEDW_EPS_2015ON
	ADD COLUMN FIRST_OPCS_DT DATE;

INSERT INTO SAILW0572V.VB_PEDW_FIRST_OPCS_INSTANCE_UNIQUE
	(SELECT eps.EPI_ID,
			MIN(eps.AVAILABLE_FROM_DT)
		FROM SAILW0572V.VB_PEDW_FIRST_OPCS_INSTANCE AS eps
			GROUP BY eps.EPI_ID);
		
UPDATE SAILW0572V.VB_PEDW_FIRST_OPCS_INSTANCE_UNIQUE AS fst
	SET fst.FIRST_OPCS_DT = CASE WHEN fst.FIRST_OPCS_DT < (SELECT min(dts.EXTRACT_DT) FROM SAILW0572V.VB_PEDW_EXTRACT_DATES AS dts)
			THEN (SELECT min(dts.EXTRACT_DT) FROM SAILW0572V.VB_PEDW_EXTRACT_DATES AS dts)
	ELSE fst.FIRST_OPCS_DT
		END;
	
UPDATE SAILW0572V.VB_PEDW_EPS_2015ON eps
	SET eps.FIRST_OPCS_DT = (SELECT fst.FIRST_OPCS_DT
	FROM SAILW0572V.VB_PEDW_FIRST_OPCS_INSTANCE_UNIQUE AS fst
			WHERE eps.EPI_ID = fst.EPI_ID)
			WHERE eps.OPER_CD IS NOT NULL;
		
/* RMarkdown is now ready to run ensuring user entered variables chunk has been updated with latest dates */